//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoThueXe.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_phatsinhxe")]
    public partial class tbl_phatsinhxe
    {   
        [Key]
        public short Sttps { get; set; }
        public string Sttphieu { get; set; }
        public string Soxedkcu { get; set; }
        public string Soxethay { get; set; }
    
        public virtual tbl_phieudk tbl_phieudk { get; set; }
    }
}
