//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoThueXe.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_dinhgia")]
    public partial class tbl_dinhgia
    {
        [Key]
        [Column(Order = 1)]
        public string Mahangxe { get; set; }
        [Key]
        [Column(Order = 2)]
        public string Manv { get; set; }
        [Key]
        [Column(Order = 3)]
        public short Thang { get; set; }
        [Key]
        [Column(Order = 4)]
        public short Nam { get; set; }
        public Nullable<decimal> Giathue { get; set; }
    
        public virtual tbl_hangxe tbl_hangxe { get; set; }
        public virtual tbl_nhanvien tbl_nhanvien { get; set; }
    }
}
