//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoThueXe.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_nhanvien")]
    public partial class tbl_nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_nhanvien()
        {
            this.tbl_dinhgia = new HashSet<tbl_dinhgia>();
            this.tbl_laplichxe = new HashSet<tbl_laplichxe>();
            this.tbl_phieudk = new HashSet<tbl_phieudk>();
        }
        [Key]
        public string Manv { get; set; }
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<short> Namsinh { get; set; }
        public string Sodt { get; set; }
        public string Macv { get; set; }
    
        public virtual tbl_chucvu tbl_chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_dinhgia> tbl_dinhgia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_laplichxe> tbl_laplichxe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_phieudk> tbl_phieudk { get; set; }
    }
}
