//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoThueXe.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tbl_phieudk")]
    public partial class tbl_phieudk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_phieudk()
        {
            this.tbl_dangkyxe = new HashSet<tbl_dangkyxe>();
            this.tbl_phatsinhxe = new HashSet<tbl_phatsinhxe>();
        }
        [Key]
        public string Sttphieu { get; set; }
        public Nullable<System.DateTime> Ngayghi { get; set; }
        public string Manv { get; set; }
        public string Maso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_dangkyxe> tbl_dangkyxe { get; set; }
        public virtual tbl_khach tbl_khach { get; set; }
        public virtual tbl_nhanvien tbl_nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_phatsinhxe> tbl_phatsinhxe { get; set; }
    }
}
